import { apiRequest, ApiError } from '../services/api';
import { confirmAction, showError, showFormDialog } from '../ui/dialog';

type PageName='Inventory'|'Stock Tracking'|'Categories'|'Locations'|'Reports'|'Settings';
const esc=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const formatPeso=(value:number|string)=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP',minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(value)||0);
const empty=(message:string)=>`<div class="module-empty"><strong>No records found</strong><span>${message}</span></div>`;
const shell=(title:string,description:string,actions='',body='')=>`<section class="module-view"><div class="module-heading"><div><h2>${title}</h2><p>${description}</p></div><div class="module-actions">${actions}</div></div><div class="module-body">${body||'<div class="module-loading">Loading data…</div>'}</div></section>`;
const button=(id:string,label:string,primary=false)=>`<button id="${id}" class="module-button ${primary?'primary':''}">${label}</button>`;

type TableState={page:number;limit:number;total:number;search:string};
const perPageOptions=(selected:number)=>[10,15,20].map(value=>`<option value="${value}" ${value===selected?'selected':''}>${value}</option>`).join('');
const pagination=(state:TableState)=>{const start=state.total?(state.page-1)*state.limit+1:0;const end=Math.min(state.page*state.limit,state.total);const pages=Math.max(1,Math.ceil(state.total/state.limit));return`<div class="table-pagination"><span>Showing <b>${start}–${end}</b> of <b>${state.total}</b></span><label>Rows per page <select class="per-page">${perPageOptions(state.limit)}</select></label><div><button class="page-prev" ${state.page<=1?'disabled':''}>Previous</button><span>Page ${state.page} of ${pages}</span><button class="page-next" ${state.page>=pages?'disabled':''}>Next</button></div></div>`;};
const bindPagination=(body:HTMLElement,state:TableState,load:()=>Promise<void>)=>{body.querySelector<HTMLSelectElement>('.per-page')?.addEventListener('change',event=>{state.limit=Number((event.target as HTMLSelectElement).value);state.page=1;void load();});body.querySelector<HTMLButtonElement>('.page-prev')?.addEventListener('click',()=>{if(state.page>1){state.page--;void load();}});body.querySelector<HTMLButtonElement>('.page-next')?.addEventListener('click',()=>{if(state.page*state.limit<state.total){state.page++;void load();}});};
const bindSearch=(input:HTMLInputElement|undefined,onChange:(value:string)=>void)=>{if(!input)return;let timer=0;input.addEventListener('input',()=>{window.clearTimeout(timer);timer=window.setTimeout(()=>onChange(input.value.trim()),250);});};
const bindRowMenus=(body:HTMLElement)=>{const close=()=>{body.querySelectorAll<HTMLElement>('.row-menu-popover.show').forEach(menu=>{menu.classList.remove('show');menu.style.removeProperty('left');menu.style.removeProperty('top');menu.previousElementSibling?.setAttribute('aria-expanded','false');});};body.querySelectorAll<HTMLButtonElement>('.kebab-button').forEach(button=>button.addEventListener('click',event=>{event.stopPropagation();const menu=button.nextElementSibling as HTMLElement;const opening=!menu.classList.contains('show');close();if(!opening)return;menu.classList.add('show');button.setAttribute('aria-expanded','true');if(innerWidth>650){const rect=button.getBoundingClientRect();const width=menu.offsetWidth;const height=menu.offsetHeight;menu.style.left=`${Math.max(8,Math.min(innerWidth-width-8,rect.right-width))}px`;menu.style.top=`${rect.bottom+height+8>innerHeight?Math.max(8,rect.top-height-6):rect.bottom+6}px`;}}));body.onclick=close;body.querySelector('.module-table-wrap')?.addEventListener('scroll',close,{passive:true});};

export async function ensureSession():Promise<boolean>{try{await apiRequest('/auth/me');return true;}catch{return false;}}
export function showLogin(onSuccess:()=>void){
  const overlay=document.createElement('div');
  const rememberedEmail=localStorage.getItem('stockhub.rememberedEmail')??'';
  overlay.className='login-overlay';
  overlay.innerHTML=`<main class="login-shell">
    <section class="login-visual" aria-label="Inventory Management System">
      <div class="login-visual-shade"></div>
      <div class="login-identity">
        <svg viewBox="0 0 96 78" aria-hidden="true"><path d="M12 69V29L48 8l36 21v40H67V40H29v29Z"/><path d="M35 45h26v24H35zM48 45v24M35 55h26"/></svg>
        <strong>INVENTORY</strong><span>MANAGEMENT SYSTEM</span><i></i>
        <p>Track. Manage. Optimize.<br>All your inventory in one place.</p>
      </div>
      <div class="login-features" aria-label="System features">
        <div><span>▣</span><b>Real-time<br>Tracking</b></div>
        <div><span>▥</span><b>Stock<br>Analytics</b></div>
        <div><span>♧</span><b>Low Stock<br>Alerts</b></div>
        <div><span>⌖</span><b>Location<br>Management</b></div>
      </div>
    </section>
    <section class="login-form-side">
      <form class="login-card">
        <div class="login-shield" aria-hidden="true"><svg viewBox="0 0 48 54"><path d="M24 3c7 6 13 7 20 8v13c0 13-8 22-20 28C12 46 4 37 4 24V11c7-1 13-2 20-8Z"/><rect x="17" y="24" width="14" height="12" rx="2"/><path d="M20 24v-4a4 4 0 0 1 8 0v4M24 29v3"/></svg></div>
        <h2>Welcome Back!</h2><p>Sign in to continue to your account</p>
        <label>Username
          <span class="login-input"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></svg><input name="email" type="email" required autocomplete="username" placeholder="Enter your email" value="${esc(rememberedEmail)}"></span>
        </label>
        <label>Password
          <span class="login-input"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="4" y="10" width="16" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3M12 14v3"/></svg><input name="password" type="password" required autocomplete="current-password" placeholder="Enter your password"><button class="password-toggle" type="button" aria-label="Show password" aria-pressed="false"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/></svg></button></span>
        </label>
        <div class="login-options"><label class="remember-option"><input name="remember" type="checkbox" ${rememberedEmail?'checked':''}><span>Remember me</span></label><button class="forgot-password" type="button">Forgot password?</button></div>
        <div class="login-error" role="alert" aria-live="polite"></div>
        <button class="login-submit" type="submit"><span aria-hidden="true">⇥</span><span>Sign In</span></button>
      </form>
      <footer>© ${new Date().getFullYear()} StockHub Inventory Management System. All rights reserved.</footer>
    </section>
  </main>`;
  document.body.append(overlay);
  const form=overlay.querySelector<HTMLFormElement>('form')!;
  const password=form.elements.namedItem('password') as HTMLInputElement;
  const toggle=overlay.querySelector<HTMLButtonElement>('.password-toggle')!;
  toggle.onclick=()=>{const visible=password.type==='text';password.type=visible?'password':'text';toggle.setAttribute('aria-pressed',String(!visible));toggle.setAttribute('aria-label',visible?'Show password':'Hide password');};
  overlay.querySelector<HTMLButtonElement>('.forgot-password')!.onclick=()=>{overlay.querySelector<HTMLElement>('.login-error')!.textContent='Ask an administrator to reset your StockHub password.';};
  form.addEventListener('submit',async e=>{e.preventDefault();const data=new FormData(form);const error=overlay.querySelector<HTMLElement>('.login-error')!;const submit=overlay.querySelector<HTMLButtonElement>('.login-submit')!;error.textContent='';submit.disabled=true;submit.lastElementChild!.textContent='Signing In…';try{await apiRequest('/auth/login',{method:'POST',body:JSON.stringify({email:data.get('email'),password:data.get('password')})});if(data.get('remember'))localStorage.setItem('stockhub.rememberedEmail',String(data.get('email')));else localStorage.removeItem('stockhub.rememberedEmail');overlay.remove();onSuccess();}catch(reason){error.textContent=reason instanceof Error?reason.message:'Sign in failed.';submit.disabled=false;submit.lastElementChild!.textContent='Sign In';}});
}

async function inventory(root:HTMLElement){
  const session:any=await apiRequest('/auth/me');const isAdmin=session.user.role==='ADMIN';
  root.innerHTML=shell('Inventory','Manage items, stock levels, and warehouse assignments.',button('refreshItems','Refresh')+(isAdmin?button('addInventory','+ Add Item',true):''));
  const load=async()=>{const body=root.querySelector<HTMLElement>('.module-body')!;try{const data:any=await apiRequest('/items?page=1&limit=100');body.innerHTML=data.items.length?`<div class="module-table-wrap"><table class="module-table"><thead><tr><th>SKU</th><th>Item</th><th>Category</th><th>Location</th><th>Quantity</th><th>Unit Cost</th><th>Status</th><th>Actions</th></tr></thead><tbody>${data.items.map((item:any)=>`<tr><td>${esc(item.sku)}</td><td class="full-name-cell"><b>${esc(item.name)}</b><small>${esc(item.description||'')}</small></td><td>${esc(item.category)}</td><td>${esc(item.locationCode)}</td><td>${esc(item.quantity)}</td><td>${formatPeso(item.unitCost)}</td><td><span class="pill ${item.stockStatus==='In Stock'?'green':'orange'}">${esc(item.stockStatus)}</span></td><td class="row-menu-cell"><div class="row-menu"><button class="kebab-button" type="button" aria-label="Actions for ${esc(item.name)}" aria-expanded="false">⋮</button><div class="row-menu-popover"><button class="stock-in" data-id="${item.id}">Stock In</button><button class="stock-out" data-id="${item.id}">Stock Out</button>${isAdmin?`<button class="edit-item" data-id="${item.id}">Edit</button><button class="danger archive-item" data-id="${item.id}">Delete</button>`:''}</div></div></td></tr>`).join('')}</tbody></table></div>`:empty('Add your first inventory item.');
    body.querySelectorAll<HTMLButtonElement>('.kebab-button').forEach(button=>button.onclick=event=>{event.stopPropagation();const menu=button.nextElementSibling as HTMLElement;body.querySelectorAll<HTMLElement>('.row-menu-popover.show').forEach(open=>{if(open!==menu)open.classList.remove('show');});menu.classList.toggle('show');button.setAttribute('aria-expanded',String(menu.classList.contains('show')));});
    body.onclick=()=>body.querySelectorAll<HTMLElement>('.row-menu-popover.show').forEach(open=>open.classList.remove('show'));
    body.querySelectorAll<HTMLButtonElement>('.stock-in,.stock-out').forEach(control=>control.onclick=async()=>{const item=data.items.find((entry:any)=>entry.id===Number(control.dataset.id));const direction=control.classList.contains('stock-in')?'in':'out';const values=await showFormDialog(`${direction==='in'?'Stock In':'Stock Out'} — ${item.name}`,[{name:'quantity',label:'Quantity',type:'number',min:.01,step:.01,required:true},{name:'reason',label:'Reason or reference',type:'textarea',required:true}],direction==='in'?'Add Stock':'Remove Stock');if(!values)return;const quantity=Number(values.quantity);if(!Number.isFinite(quantity)||quantity<=0){showError('Enter a quantity greater than zero.','Invalid quantity');return;}try{await apiRequest(`/stock/${direction}`,{method:'POST',body:JSON.stringify({itemId:item.id,quantity,reason:values.reason})});await load();window.dispatchEvent(new CustomEvent('stockhub:mutation',{detail:{refreshCurrent:false}}));}catch(error){showError(error instanceof Error?error.message:'Operation failed.','Stock operation failed');}});
    body.querySelectorAll<HTMLButtonElement>('.edit-item').forEach(control=>control.onclick=async()=>{const item=data.items.find((entry:any)=>entry.id===Number(control.dataset.id));try{const categories:any[]=await apiRequest('/categories');const values=await showFormDialog(`Edit ${item.name}`,[{name:'name',label:'Item name',value:item.name,required:true},{name:'description',label:'Description',value:item.description,type:'textarea'},{name:'categoryId',label:'Category',value:item.categoryId,type:'select',options:categories.map((entry:any)=>({label:entry.name,value:String(entry.id)}))},{name:'unitCost',label:'Unit cost (PHP ₱)',value:item.unitCost,type:'number',min:0,step:.01,required:true},{name:'reorderLevel',label:'Reorder level',value:item.reorderLevel,type:'number',min:0,required:true},{name:'maximumStock',label:'Maximum stock',value:item.maximumStock,type:'number',min:0}]);if(!values)return;await apiRequest(`/items/${item.id}`,{method:'PUT',body:JSON.stringify({name:values.name,description:values.description,categoryId:Number(values.categoryId),unitCost:Number(values.unitCost),reorderLevel:Number(values.reorderLevel),maximumStock:values.maximumStock?Number(values.maximumStock):null})});await load();window.dispatchEvent(new CustomEvent('stockhub:mutation',{detail:{refreshCurrent:false}}));}catch(error){showError(error instanceof Error?error.message:'Item could not be updated.');}});
    body.querySelectorAll<HTMLButtonElement>('.archive-item').forEach(control=>control.onclick=async()=>{const item=data.items.find((entry:any)=>entry.id===Number(control.dataset.id));if(!await confirmAction(`Delete ${item.name}? Its transaction history will be preserved.`,'Delete inventory item'))return;try{await apiRequest(`/items/${item.id}`,{method:'DELETE'});await load();window.dispatchEvent(new CustomEvent('stockhub:mutation',{detail:{refreshCurrent:false}}));}catch(error){showError(error instanceof Error?error.message:'Item could not be deleted.');}});
  }catch(error){body.innerHTML=empty(error instanceof ApiError&&error.status===401?'Please sign in to view inventory.':'Inventory could not be loaded.');}};
  root.querySelector<HTMLButtonElement>('#refreshItems')!.onclick=load;root.querySelector<HTMLButtonElement>('#addInventory')?.addEventListener('click',()=>document.querySelector<HTMLButtonElement>('#quickAdd')?.click());await load();
}

async function transactions(root:HTMLElement){root.innerHTML=shell('Stock Tracking','Complete audit trail of inventory quantity changes.',button('refreshTransactions','Refresh'));const load=async()=>{const body=root.querySelector<HTMLElement>('.module-body')!;try{const data:any=await apiRequest('/transactions?limit=100');body.innerHTML=data.transactions.length?`<div class="module-table-wrap"><table class="module-table"><thead><tr><th>Date</th><th>SKU</th><th>Item</th><th>Type</th><th>Change</th><th>Previous → New</th><th>User</th><th>Reason</th></tr></thead><tbody>${data.transactions.map((t:any)=>`<tr><td>${new Date(t.createdAt).toLocaleString()}</td><td>${esc(t.sku)}</td><td>${esc(t.item)}</td><td>${esc(t.transactionType)}</td><td>${Number(t.quantityChange)>0?'+':''}${esc(t.quantityChange)}</td><td>${esc(t.previousQuantity)} → ${esc(t.newQuantity)}</td><td>${esc(t.performedBy)}</td><td>${esc(t.remarks)}</td></tr>`).join('')}</tbody></table></div>`:empty('Stock transactions will appear here.');}catch{body.innerHTML=empty('Transaction history could not be loaded.');}};root.querySelector<HTMLButtonElement>('#refreshTransactions')!.onclick=load;await load();}

async function inventoryPaged(root:HTMLElement){
  const session:any=await apiRequest('/auth/me');const isAdmin=session.user.role==='ADMIN';const canStock=isAdmin||session.user.role==='STAFF';
  const state:TableState={page:1,limit:10,total:0,search:''};let categoryId=sessionStorage.getItem('stockhub.inventoryCategory')??'';sessionStorage.removeItem('stockhub.inventoryCategory');let status='all';const categories:any[]=await apiRequest('/categories');
  root.innerHTML=shell('Inventory','Manage items, stock levels, and warehouse assignments.',button('refreshItems','Refresh')+(isAdmin?button('addInventory','+ Add Item',true):''));
  const load=async()=>{const body=root.querySelector<HTMLElement>('.module-body')!;try{
    const params=new URLSearchParams({page:String(state.page),limit:String(state.limit),search:state.search,status});if(categoryId)params.set('categoryId',categoryId);const data:any=await apiRequest(`/items?${params}`);state.total=data.total;if(!data.items.length&&state.page>1){state.page--;return load();}
    const toolbar=`<div class="table-filterbar"><label class="table-search-wrap"><span>Search</span><input class="table-search" value="${esc(state.search)}" placeholder="Item name, SKU, category or location"></label><label><span>Category</span><select class="category-filter"><option value="">All categories</option>${categories.map(category=>`<option value="${category.id}" ${String(category.id)===categoryId?'selected':''}>${esc(category.name)}</option>`).join('')}</select></label><label><span>Status</span><select class="status-filter"><option value="all" ${status==='all'?'selected':''}>All statuses</option><option value="in-stock" ${status==='in-stock'?'selected':''}>In Stock</option><option value="low-stock" ${status==='low-stock'?'selected':''}>Low Stock</option><option value="out-of-stock" ${status==='out-of-stock'?'selected':''}>Out of Stock</option></select></label></div>`;
    const table=data.items.length?`<div class="module-table-wrap"><table class="module-table"><thead><tr><th>SKU</th><th>Item</th><th>Category</th><th>Location</th><th>Quantity</th><th>Unit Cost</th><th>Status</th><th>Actions</th></tr></thead><tbody>${data.items.map((item:any)=>`<tr><td>${esc(item.sku)}</td><td class="full-name-cell"><b>${esc(item.name)}</b><small>${esc(item.description||'')}</small></td><td>${esc(item.category)}</td><td>${esc(item.locationCode)}</td><td>${esc(item.quantity)}</td><td>${formatPeso(item.unitCost)}</td><td><span class="pill ${item.stockStatus==='In Stock'?'green':item.stockStatus==='Out of Stock'?'red':'orange'}">${esc(item.stockStatus)}</span></td><td class="row-menu-cell">${canStock||isAdmin?`<div class="row-menu"><button class="kebab-button" type="button" aria-label="Actions for ${esc(item.name)}" aria-expanded="false">⋮</button><div class="row-menu-popover">${canStock?`<button class="stock-in" data-id="${item.id}">Stock In</button><button class="stock-out" data-id="${item.id}">Stock Out</button>`:''}${isAdmin?`<button class="edit-item" data-id="${item.id}">Edit</button><button class="danger archive-item" data-id="${item.id}">Delete</button>`:''}</div></div>`:'—'}</td></tr>`).join('')}</tbody></table></div>`:empty('No inventory items match the selected filters.');
    body.innerHTML=toolbar+table+pagination(state);bindPagination(body,state,load);bindSearch(body.querySelector<HTMLInputElement>('.table-search')??undefined,value=>{state.search=value;state.page=1;void load();});body.querySelector<HTMLSelectElement>('.category-filter')!.onchange=event=>{categoryId=(event.target as HTMLSelectElement).value;state.page=1;void load();};body.querySelector<HTMLSelectElement>('.status-filter')!.onchange=event=>{status=(event.target as HTMLSelectElement).value;state.page=1;void load();};bindRowMenus(body);
    body.querySelectorAll<HTMLButtonElement>('.stock-in,.stock-out').forEach(control=>control.onclick=async()=>{const item=data.items.find((entry:any)=>entry.id===Number(control.dataset.id));const direction=control.classList.contains('stock-in')?'in':'out';const values=await showFormDialog(`${direction==='in'?'Stock In':'Stock Out'} — ${item.name}`,[{name:'quantity',label:'Quantity',type:'number',min:.01,step:.01,required:true},{name:'reason',label:'Reason or reference',type:'textarea',required:true}],direction==='in'?'Add Stock':'Remove Stock');if(!values)return;const quantity=Number(values.quantity);if(!Number.isFinite(quantity)||quantity<=0){showError('Enter a quantity greater than zero.','Invalid quantity');return;}try{await apiRequest(`/stock/${direction}`,{method:'POST',body:JSON.stringify({itemId:item.id,quantity,reason:values.reason})});await load();window.dispatchEvent(new CustomEvent('stockhub:mutation',{detail:{refreshCurrent:false}}));}catch(error){showError(error instanceof Error?error.message:'Operation failed.','Stock operation failed');}});
    body.querySelectorAll<HTMLButtonElement>('.edit-item').forEach(control=>control.onclick=async()=>{const item=data.items.find((entry:any)=>entry.id===Number(control.dataset.id));const values=await showFormDialog(`Edit ${item.name}`,[{name:'name',label:'Item name',value:item.name,required:true},{name:'description',label:'Description',value:item.description,type:'textarea'},{name:'categoryId',label:'Category',value:item.categoryId,type:'select',options:categories.map(entry=>({label:entry.name,value:String(entry.id)}))},{name:'unitCost',label:'Unit cost (PHP ₱)',value:item.unitCost,type:'number',min:0,step:.01,required:true},{name:'reorderLevel',label:'Reorder level',value:item.reorderLevel,type:'number',min:0,required:true},{name:'maximumStock',label:'Maximum stock',value:item.maximumStock,type:'number',min:0}]);if(!values)return;try{await apiRequest(`/items/${item.id}`,{method:'PUT',body:JSON.stringify({name:values.name,description:values.description,categoryId:Number(values.categoryId),unitCost:Number(values.unitCost),reorderLevel:Number(values.reorderLevel),maximumStock:values.maximumStock?Number(values.maximumStock):null})});await load();window.dispatchEvent(new CustomEvent('stockhub:mutation',{detail:{refreshCurrent:false}}));}catch(error){showError(error instanceof Error?error.message:'Item could not be updated.');}});
    body.querySelectorAll<HTMLButtonElement>('.archive-item').forEach(control=>control.onclick=async()=>{const item=data.items.find((entry:any)=>entry.id===Number(control.dataset.id));if(!await confirmAction(`Delete ${item.name}? Its transaction history will be preserved.`,'Delete inventory item'))return;try{await apiRequest(`/items/${item.id}`,{method:'DELETE'});await load();window.dispatchEvent(new CustomEvent('stockhub:mutation',{detail:{refreshCurrent:false}}));}catch(error){showError(error instanceof Error?error.message:'Item could not be deleted.');}});
  }catch(error){body.innerHTML=empty(error instanceof ApiError&&error.status===401?'Please sign in to view inventory.':'Inventory could not be loaded.');}};
  root.querySelector<HTMLButtonElement>('#refreshItems')!.onclick=load;root.querySelector<HTMLButtonElement>('#addInventory')?.addEventListener('click',()=>document.querySelector<HTMLButtonElement>('#quickAdd')?.click());await load();
}

async function transactionsPaged(root:HTMLElement){
  const state:TableState={page:1,limit:10,total:0,search:''};let type='all';root.innerHTML=shell('Stock Tracking','Complete audit trail of inventory quantity changes.',button('refreshTransactions','Refresh'));
  const load=async()=>{const body=root.querySelector<HTMLElement>('.module-body')!;try{const params=new URLSearchParams({page:String(state.page),limit:String(state.limit),search:state.search,type});const data:any=await apiRequest(`/transactions?${params}`);state.total=data.total;if(!data.transactions.length&&state.page>1){state.page--;return load();}const toolbar=`<div class="table-filterbar"><label class="table-search-wrap"><span>Search</span><input class="table-search" value="${esc(state.search)}" placeholder="Item, SKU, user, location or reason"></label><label><span>Type</span><select class="type-filter"><option value="all">All transaction types</option>${['INITIAL_STOCK','STOCK_IN','STOCK_OUT','ADJUSTMENT','TRANSFER_IN','TRANSFER_OUT'].map(value=>`<option value="${value}" ${type===value?'selected':''}>${value.replaceAll('_',' ')}</option>`).join('')}</select></label></div>`;const table=data.transactions.length?`<div class="module-table-wrap"><table class="module-table"><thead><tr><th>Date</th><th>SKU</th><th>Item</th><th>Type</th><th>Change</th><th>Previous → New</th><th>User</th><th>Reason</th></tr></thead><tbody>${data.transactions.map((t:any)=>`<tr><td>${new Date(t.createdAt).toLocaleString()}</td><td>${esc(t.sku)}</td><td>${esc(t.item)}</td><td>${esc(t.transactionType)}</td><td>${Number(t.quantityChange)>0?'+':''}${esc(t.quantityChange)}</td><td>${esc(t.previousQuantity)} → ${esc(t.newQuantity)}</td><td>${esc(t.performedBy)}</td><td>${esc(t.remarks)}</td></tr>`).join('')}</tbody></table></div>`:empty('No transactions match the selected filters.');body.innerHTML=toolbar+table+pagination(state);bindPagination(body,state,load);bindSearch(body.querySelector<HTMLInputElement>('.table-search')??undefined,value=>{state.search=value;state.page=1;void load();});body.querySelector<HTMLSelectElement>('.type-filter')!.onchange=event=>{type=(event.target as HTMLSelectElement).value;state.page=1;void load();};}catch{body.innerHTML=empty('Transaction history could not be loaded.');}};root.querySelector<HTMLButtonElement>('#refreshTransactions')!.onclick=load;await load();
}

async function categories(root:HTMLElement){
  const session:any=await apiRequest('/auth/me');const isAdmin=session.user.role==='ADMIN';root.innerHTML=shell('Categories','Organize inventory using reusable categories.',isAdmin?button('addCategory','+ Add Category',true):'');
  const load=async()=>{const body=root.querySelector<HTMLElement>('.module-body')!;try{const data:any[]=await apiRequest('/categories');body.innerHTML=data.length?`<div class="module-grid">${data.map(category=>`<article class="record-card"><span>Category</span><h3>${esc(category.name)}</h3><p>${esc(category.description||'No description')}</p>${isAdmin?`<div class="record-actions"><button class="mini-action edit-category" data-id="${category.id}">Rename / Edit</button><button class="mini-action danger delete-category" data-id="${category.id}">Delete</button></div>`:''}</article>`).join('')}</div>`:empty('Create a category to organize items.');
    body.querySelectorAll<HTMLButtonElement>('.edit-category').forEach(control=>control.onclick=async()=>{const category=data.find(entry=>entry.id===Number(control.dataset.id));const values=await showFormDialog('Edit category',[{name:'name',label:'Category name',value:category.name,required:true},{name:'description',label:'Description',value:category.description,type:'textarea'}]);if(!values)return;try{await apiRequest(`/categories/${category.id}`,{method:'PUT',body:JSON.stringify(values)});await load();window.dispatchEvent(new CustomEvent('stockhub:mutation',{detail:{refreshCurrent:false}}));}catch(error){showError(error instanceof Error?error.message:'Category could not be updated.');}});
    body.querySelectorAll<HTMLButtonElement>('.delete-category').forEach(control=>control.onclick=async()=>{const category=data.find(entry=>entry.id===Number(control.dataset.id));if(!await confirmAction(`Delete the “${category.name}” category? Existing item records will remain intact.`,'Delete category'))return;try{await apiRequest(`/categories/${category.id}`,{method:'DELETE'});await load();window.dispatchEvent(new CustomEvent('stockhub:mutation',{detail:{refreshCurrent:false}}));}catch(error){showError(error instanceof Error?error.message:'Category could not be deleted.');}});
  }catch{body.innerHTML=empty('Categories could not be loaded.');}};
  root.querySelector<HTMLButtonElement>('#addCategory')?.addEventListener('click',async()=>{const values=await showFormDialog('Create category',[{name:'name',label:'Category name',required:true},{name:'description',label:'Description',type:'textarea'}],'Create');if(!values)return;try{await apiRequest('/categories',{method:'POST',body:JSON.stringify(values)});await load();window.dispatchEvent(new CustomEvent('stockhub:mutation',{detail:{refreshCurrent:false}}));}catch(error){showError(error instanceof Error?error.message:'Category could not be created.');}});await load();
}

async function categoriesStyled(root:HTMLElement){
  const session:any=await apiRequest('/auth/me');const isAdmin=session.user.role==='ADMIN';let all:any[]=[];let search='';let status='all';let sort='name-asc';let view:'grid'|'list'='grid';
  const categoryIcon=(index:number)=>{const symbols=[`<path d="M5 8.5 12 4l7 4.5v8L12 21l-7-4.5Z"/><path d="m5 8.5 7 4.5 7-4.5M12 13v8"/>`,`<path d="M4 7h16v13H4zM7 4h10v3M8 11h8M8 15h5"/>`,`<path d="m13 2-8 11h6l-1 9 9-12h-6Z"/>`,`<rect x="5" y="5" width="14" height="14" rx="2"/><path d="M9 2v3M15 2v3M9 19v3M15 19v3M2 9h3M19 9h3M2 15h3M19 15h3"/>`,`<path d="M7 4h10v9a5 5 0 0 1-10 0ZM5 21l4-4M19 21l-4-4"/>`,`<path d="M4 6h16v14H4zM8 3h8v3M8 10h8M8 14h5"/>`];return`<svg viewBox="0 0 24 24" aria-hidden="true">${symbols[index%symbols.length]}</svg>`;};
  root.innerHTML=shell('Categories','Organize your inventory using reusable categories.',isAdmin?button('addCategory','+ Add Category',true):'');root.querySelector('.module-view')?.classList.add('categories-view');
  const render=()=>{const body=root.querySelector<HTMLElement>('.module-body')!;const active=all.filter(category=>Boolean(category.isActive)).length;const archived=all.length-active;const totalItems=all.reduce((sum,category)=>sum+Number(category.itemCount||0),0);let visible=all.filter(category=>(status==='all'||(status==='active')===Boolean(category.isActive))&&(category.name.toLowerCase().includes(search.toLowerCase())||String(category.description||'').toLowerCase().includes(search.toLowerCase())));visible=[...visible].sort((a,b)=>sort==='name-desc'?b.name.localeCompare(a.name):sort==='items-desc'?Number(b.itemCount)-Number(a.itemCount):sort==='items-asc'?Number(a.itemCount)-Number(b.itemCount):a.name.localeCompare(b.name));
    body.innerHTML=`<section class="category-stats"><article><span class="category-stat-icon blue">${categoryIcon(0)}</span><div><small>Total Categories</small><b>${all.length}</b><p>${active} active categories</p></div></article><article><span class="category-stat-icon green">${categoryIcon(1)}</span><div><small>Active Categories</small><b>${active}</b><p>Currently in use</p></div></article><article><span class="category-stat-icon orange">${categoryIcon(5)}</span><div><small>Archived Categories</small><b>${archived}</b><p>${archived?'Kept for historical records':'No archived categories'}</p></div></article><article><span class="category-stat-icon purple">${categoryIcon(3)}</span><div><small>Total Items</small><b>${totalItems.toLocaleString()}</b><p>Across all categories</p></div></article></section>
    <section class="category-toolbar"><label class="category-search"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg><input class="table-search" value="${esc(search)}" placeholder="Search categories..."></label><div class="category-toolbar-actions"><label><span>Status:</span><select class="category-status"><option value="all" ${status==='all'?'selected':''}>All</option><option value="active" ${status==='active'?'selected':''}>Active</option><option value="archived" ${status==='archived'?'selected':''}>Archived</option></select></label><label><span>Sort:</span><select class="category-sort"><option value="name-asc" ${sort==='name-asc'?'selected':''}>Name (A–Z)</option><option value="name-desc" ${sort==='name-desc'?'selected':''}>Name (Z–A)</option><option value="items-desc" ${sort==='items-desc'?'selected':''}>Most items</option><option value="items-asc" ${sort==='items-asc'?'selected':''}>Fewest items</option></select></label><div class="category-view-toggle"><button class="grid-view ${view==='grid'?'active':''}" aria-label="Grid view">▦</button><button class="list-view ${view==='list'?'active':''}" aria-label="List view">☷</button></div><button class="category-export">⇩ Export</button></div></section>
    ${visible.length?`<section class="category-card-grid ${view==='list'?'list-mode':''}">${visible.map((category,index)=>`<article class="category-card"><div class="category-card-main"><span class="category-card-icon tone-${index%6}">${categoryIcon(index)}</span><div><div class="category-card-title"><h3>${esc(category.name)}</h3><span class="category-state ${category.isActive?'active':'archived'}">${category.isActive?'Active':'Archived'}</span></div><b>${Number(category.itemCount||0).toLocaleString()} items</b><p>${esc(category.description||'No description provided.')}</p></div></div><footer><button class="view-category-items" data-id="${category.id}">View Items</button>${isAdmin&&category.isActive?`<button class="edit-category" data-id="${category.id}">✎ Edit</button><button class="delete-category" data-id="${category.id}" aria-label="Delete ${esc(category.name)}"><svg viewBox="0 0 24 24"><path d="M4 7h16M9 7V4h6v3M8 10v8M12 10v8M16 10v8M6 7l1 14h10l1-14"/></svg></button>`:''}</footer></article>`).join('')}</section>`:empty('No categories match the selected filters.')}`;
    const input=body.querySelector<HTMLInputElement>('.category-search input')!;bindSearch(input,value=>{search=value;render();});body.querySelector<HTMLSelectElement>('.category-status')!.onchange=event=>{status=(event.target as HTMLSelectElement).value;render();};body.querySelector<HTMLSelectElement>('.category-sort')!.onchange=event=>{sort=(event.target as HTMLSelectElement).value;render();};body.querySelector<HTMLButtonElement>('.grid-view')!.onclick=()=>{view='grid';render();};body.querySelector<HTMLButtonElement>('.list-view')!.onclick=()=>{view='list';render();};
    body.querySelector<HTMLButtonElement>('.category-export')!.onclick=()=>{const csv=['Category,Status,Items,Description',...visible.map(category=>[category.name,category.isActive?'Active':'Archived',category.itemCount||0,category.description||''].map(value=>`"${String(value).replaceAll('"','""')}"`).join(','))].join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const link=document.createElement('a');link.href=url;link.download='stockhub-categories.csv';link.click();URL.revokeObjectURL(url);};
    body.querySelectorAll<HTMLButtonElement>('.view-category-items').forEach(control=>control.onclick=()=>{sessionStorage.setItem('stockhub.inventoryCategory',String(control.dataset.id));const globalSearch=document.querySelector<HTMLInputElement>('#globalSearch');if(globalSearch)globalSearch.value='';document.querySelector<HTMLButtonElement>('.nav-item[data-label="Inventory"]')?.click();});
    body.querySelectorAll<HTMLButtonElement>('.edit-category').forEach(control=>control.onclick=async()=>{const category=all.find(entry=>entry.id===Number(control.dataset.id));const values=await showFormDialog('Edit category',[{name:'name',label:'Category name',value:category.name,required:true},{name:'description',label:'Description',value:category.description,type:'textarea'}]);if(!values)return;try{await apiRequest(`/categories/${category.id}`,{method:'PUT',body:JSON.stringify(values)});await load();window.dispatchEvent(new CustomEvent('stockhub:mutation',{detail:{refreshCurrent:false}}));}catch(error){showError(error instanceof Error?error.message:'Category could not be updated.');}});
    body.querySelectorAll<HTMLButtonElement>('.delete-category').forEach(control=>control.onclick=async()=>{const category=all.find(entry=>entry.id===Number(control.dataset.id));if(!await confirmAction(`Delete the “${category.name}” category? It will be archived and its item history will remain available.`,'Delete category'))return;try{await apiRequest(`/categories/${category.id}`,{method:'DELETE'});await load();window.dispatchEvent(new CustomEvent('stockhub:mutation',{detail:{refreshCurrent:false}}));}catch(error){showError(error instanceof Error?error.message:'Category could not be deleted.');}});
  };
  const load=async()=>{const body=root.querySelector<HTMLElement>('.module-body')!;try{all=await apiRequest('/categories?includeArchived=true');render();}catch{body.innerHTML=empty('Categories could not be loaded.');}};
  root.querySelector<HTMLButtonElement>('#addCategory')?.addEventListener('click',async()=>{const values=await showFormDialog('Create category',[{name:'name',label:'Category name',required:true},{name:'description',label:'Description',type:'textarea'}],'Create');if(!values)return;try{await apiRequest('/categories',{method:'POST',body:JSON.stringify(values)});await load();window.dispatchEvent(new CustomEvent('stockhub:mutation',{detail:{refreshCurrent:false}}));}catch(error){showError(error instanceof Error?error.message:'Category could not be created.');}});await load();
}

async function locations(root:HTMLElement){
  const session:any=await apiRequest('/auth/me');const isAdmin=session.user.role==='ADMIN';root.innerHTML=shell('Warehouse Locations','Review capacity and utilization across physical storage locations.',button('refreshLocations','Refresh')+(isAdmin?button('addLocation','+ Add Location',true):''));let current:any[]=[];
  const load=async()=>{const body=root.querySelector<HTMLElement>('.module-body')!;try{current=await apiRequest('/locations');body.innerHTML=current.length?`<div class="module-grid">${current.map(location=>{const pct=location.maximumCapacity?Math.round(Number(location.currentUsage)/Number(location.maximumCapacity)*100):0;return`<article class="record-card"><span>${esc(location.locationType)}</span><h3>${esc(location.name)} <small>${esc(location.code)}</small></h3><div class="record-progress"><i style="width:${Math.min(100,pct)}%"></i></div><p>${pct}% used · ${esc(location.currentUsage)} / ${esc(location.maximumCapacity)} units</p>${isAdmin?`<div class="record-actions"><button class="mini-action edit-location" data-id="${location.id}">Rename / Edit</button><button class="mini-action danger delete-location" data-id="${location.id}">Delete</button></div>`:''}</article>`}).join('')}</div>`:empty('No warehouse locations exist.');
    body.querySelectorAll<HTMLButtonElement>('.edit-location').forEach(control=>control.onclick=async()=>{const location=current.find(entry=>entry.id===Number(control.dataset.id));const values=await showFormDialog('Edit location',[{name:'name',label:'Location name',value:location.name,required:true},{name:'maximumCapacity',label:'Maximum capacity',value:location.maximumCapacity,type:'number',min:0,required:true},{name:'description',label:'Description',value:location.description,type:'textarea'}]);if(!values)return;try{await apiRequest(`/locations/${location.id}`,{method:'PUT',body:JSON.stringify({name:values.name,maximumCapacity:Number(values.maximumCapacity),description:values.description})});await load();window.dispatchEvent(new CustomEvent('stockhub:mutation',{detail:{refreshCurrent:false}}));}catch(error){showError(error instanceof Error?error.message:'Location could not be updated.');}});
    body.querySelectorAll<HTMLButtonElement>('.delete-location').forEach(control=>control.onclick=async()=>{const location=current.find(entry=>entry.id===Number(control.dataset.id));if(!await confirmAction(`Delete ${location.name}? Empty sublocations will also be removed from active use.`,'Delete location'))return;try{await apiRequest(`/locations/${location.id}`,{method:'DELETE'});await load();window.dispatchEvent(new CustomEvent('stockhub:mutation',{detail:{refreshCurrent:false}}));}catch(error){showError(error instanceof Error?error.message:'Location could not be deleted.');}});
  }catch{body.innerHTML=empty('Locations could not be loaded.');}};
  root.querySelector<HTMLButtonElement>('#refreshLocations')!.onclick=load;root.querySelector<HTMLButtonElement>('#addLocation')?.addEventListener('click',async()=>{const values=await showFormDialog('Create location',[{name:'code',label:'Location code',required:true},{name:'name',label:'Location name',required:true},{name:'locationType',label:'Location type',type:'select',options:['WAREHOUSE','SECTION','SLOT','STORAGE'].map(value=>({label:value,value}))},{name:'parentLocationId',label:'Parent location',type:'select',options:[{label:'None',value:''},...current.map(location=>({label:`${location.name} (${location.code})`,value:String(location.id)}))]},{name:'maximumCapacity',label:'Maximum capacity',type:'number',min:0,required:true},{name:'description',label:'Description',type:'textarea'}],'Create');if(!values)return;try{await apiRequest('/locations',{method:'POST',body:JSON.stringify({code:values.code,name:values.name,locationType:values.locationType,parentLocationId:values.parentLocationId?Number(values.parentLocationId):null,maximumCapacity:Number(values.maximumCapacity),description:values.description})});await load();window.dispatchEvent(new CustomEvent('stockhub:mutation',{detail:{refreshCurrent:false}}));}catch(error){showError(error instanceof Error?error.message:'Location could not be created.');}});await load();
}

async function reports(root:HTMLElement){root.innerHTML=shell('Reports','Live inventory valuation and category breakdown.',button('refreshReports','Refresh'));const load=async()=>{const body=root.querySelector<HTMLElement>('.module-body')!;try{const [summary,categories]:any[]=await Promise.all([apiRequest('/reports/inventory-summary'),apiRequest('/reports/category-breakdown')]);body.innerHTML=`<div class="report-stats"><article><span>Total Items</span><b>${esc(summary.totalItems)}</b></article><article><span>Total Units</span><b>${esc(summary.totalUnits)}</b></article><article><span>Inventory Value</span><b>${formatPeso(summary.inventoryValue)}</b></article><article><span>Low / Out</span><b>${esc(summary.lowStockItems)} / ${esc(summary.outOfStockItems)}</b></article></div><div class="module-table-wrap"><table class="module-table"><thead><tr><th>Category</th><th>SKUs</th><th>Units</th><th>Value (PHP)</th></tr></thead><tbody>${categories.map((c:any)=>`<tr><td>${esc(c.category)}</td><td>${esc(c.skuCount)}</td><td>${esc(c.totalUnits)}</td><td>${formatPeso(c.inventoryValue)}</td></tr>`).join('')}</tbody></table></div>`;}catch{body.innerHTML=empty('Reports could not be loaded.');}};root.querySelector<HTMLButtonElement>('#refreshReports')!.onclick=load;await load();}

async function settings(root:HTMLElement){root.innerHTML=shell('Settings','Account, session, and system configuration.','','<div class="module-loading">Loading account…</div>');const body=root.querySelector<HTMLElement>('.module-body')!;try{const data:any=await apiRequest('/auth/me');body.innerHTML=`<article class="settings-card"><div class="avatar">${esc(data.user.name.slice(0,2).toUpperCase())}</div><div><h3>${esc(data.user.name)}</h3><p>${esc(data.user.email)}</p><span class="pill green">${esc(data.user.role)}</span></div><button id="logoutUser" class="module-button">Sign out</button></article>`;body.querySelector<HTMLButtonElement>('#logoutUser')!.onclick=async()=>{await apiRequest('/auth/logout',{method:'POST'});location.reload();};}catch{body.innerHTML=empty('Account details could not be loaded.');}}

async function reportsPaged(root:HTMLElement){
  const state:TableState={page:1,limit:10,total:0,search:''};let summary:any;let categories:any[]=[];root.innerHTML=shell('Reports','Live inventory valuation and category breakdown.',button('refreshReports','Refresh'));
  const render=()=>{const body=root.querySelector<HTMLElement>('.module-body')!;const filtered=categories.filter(category=>category.category.toLowerCase().includes(state.search.toLowerCase()));state.total=filtered.length;const pages=Math.max(1,Math.ceil(state.total/state.limit));if(state.page>pages)state.page=pages;const rows=filtered.slice((state.page-1)*state.limit,state.page*state.limit);body.innerHTML=`<div class="report-stats"><article><span>Total Items</span><b>${esc(summary.totalItems)}</b></article><article><span>Total Units</span><b>${esc(summary.totalUnits)}</b></article><article><span>Inventory Value</span><b>${formatPeso(summary.inventoryValue)}</b></article><article><span>Low / Out</span><b>${esc(summary.lowStockItems)} / ${esc(summary.outOfStockItems)}</b></article></div><div class="table-filterbar"><label class="table-search-wrap"><span>Search</span><input class="table-search" value="${esc(state.search)}" placeholder="Search category"></label></div>${rows.length?`<div class="module-table-wrap"><table class="module-table"><thead><tr><th>Category</th><th>SKUs</th><th>Units</th><th>Value (PHP)</th></tr></thead><tbody>${rows.map((category:any)=>`<tr><td>${esc(category.category)}</td><td>${esc(category.skuCount)}</td><td>${esc(category.totalUnits)}</td><td>${formatPeso(category.inventoryValue)}</td></tr>`).join('')}</tbody></table></div>`:empty('No category reports match your search.')}${pagination(state)}`;bindPagination(body,state,async()=>render());bindSearch(body.querySelector<HTMLInputElement>('.table-search')??undefined,value=>{state.search=value;state.page=1;render();});};
  const load=async()=>{const body=root.querySelector<HTMLElement>('.module-body')!;try{const results:any[]=await Promise.all([apiRequest('/reports/inventory-summary'),apiRequest('/reports/category-breakdown')]);summary=results[0];categories=results[1];render();}catch{body.innerHTML=empty('Reports could not be loaded.');}};root.querySelector<HTMLButtonElement>('#refreshReports')!.onclick=load;await load();
}

export async function renderModule(name:PageName,root:HTMLElement){if(name==='Inventory')return inventoryPaged(root);if(name==='Stock Tracking')return transactionsPaged(root);if(name==='Categories')return categoriesStyled(root);if(name==='Locations')return locations(root);if(name==='Reports')return reportsPaged(root);return settings(root);}
